### ISSUE TITLE
Font Selection

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#14]
Peppermint at 1.5b4 is coming along nicely! There are huge, and improved, differences between this and 1.4.

We still need to be able to select any system font from a standard font selection panel - font and font size.

**Comment by osxpeppermint** [comment]
Done. :)

**Comment by bobrocke** [comment]
I don't see any change in 1.5b4 on the Preferences->Editor tab. Did the font selection option move?

**Comment by osxpeppermint** [comment]
Ooops... forgot to answer to this one!

Here's the font selection button: 

![fontselection](https://cloud.githubusercontent.com/assets/9476915/5626587/1be36430-9596-11e4-95f6-50bbdaa57f7f.png)

(Perhaps it's not that obvious?)

**Comment by bobrocke** [comment]
Indeed it it! And it works. You have been making changes at a crazy rate!

It's a bit odd to have both the dropdown menu and the font panel. I wonder if the preferences panel could show the selected font and size and offer the font panel to select?
