### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#15]
Please add the ability to read and apply settings from an .editorconfig file in the root of a project folder.

**Comment by bobrocke** [comment]
Is this on the upcoming release roadmap?

**Comment by osxpeppermint** [comment]
Well,... my goal is to eliminate all of the pending bugs before any "official" big release.

Now, the thing is that my topmost priorities will first be the ones that cause issues. Additions + Enhancements will follow. So, it *is* in my to-do list, but I may have to delay it just a little bit...

**Comment by osxpeppermint** [comment]
As of the upcoming 1.5 beta 19, [EditorConfig](http://editorconfig.org) support is included.

Supported properties:

- indent_style
- indent_size
- end_of_line
- max_line_length
