### ISSUE TITLE
New File Oddness

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#18]
If you click the `+` button to add a new file, it is added to the Workspace under Files rather than in a folder in the workspace. Folders cannot be selected to identify where to add the file.

After creating a file in this way, right-clicking and deleting the file or removing it from the workspace, does nothing.

**Comment by osxpeppermint** [comment]
"+" sign button removed. I think you were right - it looks rather confusing.

**Comment by osxpeppermint** [comment]
Also:

- "delete" option for temporary files has been removed (doesn't make any sense)
- "Remove from Workspace" fixed
