### ISSUE TITLE
Indentation Type Display

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#19]
Add an indication in the status bar for the file's indentation type such as `Spaces: 2` or `Tabs: 3`.

**Comment by rcrooks** [comment]
I would vote for this as well

**Comment by osxpeppermint** [comment]
Here's a question for you: 

would you prefer just a simple indication or something more like a dropdown enabling to select indentation type as well?

**Comment by bobrocke** [comment]
I'd say it should be just an indication.

Setting the indentation style for a type of file on an individual file of that type would be odd.

If .editorconfig support can be added, it can handle settings by type. Or there could be a preferences panel to do it (which would need to reflect .editorconfig, but not override it).

**Comment by osxpeppermint** [comment]
Indication just added (Beta 5) - at the "informational" left part of the status bar (next to the Line/Column indicator). For now, there might not be any document- or editorconfig- specific settings, but at least this part is there. (I'll try to integrate .editorconfig and file-specific settings by the next beta).
