### ISSUE TITLE
select first item in autocomplete menu automatically

### ISSUE THREAD

**Issue by rcrooks** [osxpeppermint/peppermint#21]
I mentioned this in an email some time back, but entering it here as an enhancement request in case you'd forgotten it.
I realize some users might *not* want this, as it increases the possibility of selecting an autocomplete item unintentionally, so others are welcome to voice their opinions. For me it's not so much an issue of having to press two keys -- I just can't shake my Sublime Text habit of pressing return to grab the first item.

**Comment by osxpeppermint** [comment]
It's in my list. Let's see :)

**Comment by osxpeppermint** [comment]
Well, rather a long time later...

As of the upcoming 1.5 Beta 15, the feature has been implemented. (along with other little-or-not enhancements: icons for different types of completions - snippet, keyword, etc -, fuzzy matching, new Yosemite-compatible style, and more!)
