### ISSUE TITLE
Console functionality

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#24]
Ioannis - In discussions you mentioned that the console should work the same as the dev console in chrome/safari. Not seeing some of that. The two images are an example of something that works in the browser console but not in Peppermint

![object](https://cloud.githubusercontent.com/assets/10382240/5602990/f8c150c0-933d-11e4-82e3-56cb84f2aae5.jpg)

![functionality](https://cloud.githubusercontent.com/assets/10382240/5602987/d9b87104-933d-11e4-9431-e3f70e8d466f.jpg)

**Comment by osxpeppermint** [comment]
Well, good catch here but the issue (?) is rather straightforward. (Btw, in Coffee mode, it's much more obvious right now, but I'm still trying to make up my mind on how this should work).

It's a scope issue.

![screen shot 2015-01-04 at 9 55 45 am](https://cloud.githubusercontent.com/assets/9476915/5605221/e77d20a4-93f7-11e4-8e40-9ce3b75112d6.png)

In a few words (js only), if you just remove the `var` keyword when assigning your `myArray` variable, the variable has a global scope, so you're able to use it. Using `var` on the other hand makes the variable `local` (which means it's only visible from within the Peppermint function executing your javascript code). :-)

**Comment by 3l3phant** [comment]
Totally understood (and makes sense). Like I said flagged it based on our email exchange. :)

**Comment by osxpeppermint** [comment]
Well, to be perfectly honest, what is returned and how it should be formatted is something that I'm still thinking over. For example, let's say you have an Object. What I'd like to do is have the object inspected pretty much as it happens in the Chrome console - which does not happen so far (although something like looping through the key-value pairs, would somewhat work, like: `for (k in obj) $Terminal.info(k + " = " + obj[k]);`)

In a few words, formatting issues (like quotes-or-no-quotes) is something that is going to be revised *very* soon. :)
