### ISSUE TITLE
copy path for files in the contextual menu for sidebar files

### ISSUE THREAD

**Issue by rcrooks** [osxpeppermint/peppermint#26]
not urgent, but a nice-to-have enhancement. Any version of the path would do....

**Comment by osxpeppermint** [comment]
Yep, that doesn't sound bad at all.

What do you mean by "version of the path"? Absolute vs relative? (I'd definitely go the "absolute" path way...)

Anyway, let's see. I've also been thinking of some sort of "quick preview" or info popup - or something along these lines (with filename / path / filesize / etc) - but I haven't made my mind up yet. Ideas?

**Comment by rcrooks** [comment]
absolute would be fine. a popup preview would be nice if it’s easy, but not essential.




  

Robert CrooksDirector of Learning Services
Brightcove, Inc

**Comment by osxpeppermint** [comment]
As of Beta No.5, the right-click menu will for now have an extra "Copy path to Clipboard" item.

The plan for a true preview though (as I described it) at some later point remains. :)

**Comment by rcrooks** [comment]
Great!
