### ISSUE TITLE
Yikes! File contents disappear on save!!!

### ISSUE THREAD

**Issue by rcrooks** [osxpeppermint/peppermint#27]
Hope this was just a one-time fluke, but I just saved an HTML file (using CMD-s) and the contents all disappeared. Undo did not revert. Fortunately the file's in Github, so I only lost a few minutes of editing.

**Comment by osxpeppermint** [comment]
Oh... well. Did this happen on 1.5 (beta 4)? Has something like that happened before?
If it's a beta4-only issue, I guess it might have to do with the change-tracking system I implemented.

**Comment by rcrooks** [comment]
Beta 4 — first time I’ve seen this happen




  

Robert CrooksDirector of Learning Services
Brightcove, Inc

**Comment by rcrooks** [comment]
by the way, I hunted to see if I could find a log that might provide some clues to what happened, but no luck. If there is one that I could look at or send to you, point me to it and I will.

**Comment by osxpeppermint** [comment]
I've performed almost all possible tests and unfortunately I haven't managed to reproduce this one - yet. I have a feeling what it *might* have been, but I still haven't reproduced. (That weird masochistic process of desperately trying to crash my own app, and then be glad when I make it! lol)

**Comment by rcrooks** [comment]
good enough — I’ll let you know if it happens again. Looking forward to
beta 5 :)

On Monday, January 5, 2015, Peppermint - Code Editor for Mac <
notifications@github.com> wrote:
> I've performed almost all possible tests and unfortunately I haven't
managed to reproduce this one - yet. I have a feeling what it might have
been, but I still haven't reproduced. (That weird masochistic process of
desperately trying to crash my own app, and then be glad when I make it!
lol)
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/leia0Ts0pzrt2XfNnW9aTiHTB4VoNrDLu5cknjbz9QjynoYguv3q1Wu6gL60uXL7MQnz1jJSRP9WhG-Tj9DhoiwWX02hM99POCdlu1dLIoU0XP_jc-NweLU42DqlEAVgm82CnANAmZ51wHqzQ-5F0HysytLiRg=s0-d-e1-ft#https://github.com/notifications/beacon/AAl0YVeOafeqHIjaTzQ8LlUqE3fNQUbPks5neqdYgaJpZM4DOBD-.gif
>

-- 
Robert Crooks
Director of Learning Services | P: 617 245 5090 | M: 617-584 6128
Brightcove Inc <http://www.brightcove.com/>

**Comment by rcrooks** [comment]
uh-oh: new variation on this one in Beta 5: opened another HTML document that I'd worked on before in another editor. When I save, the original contents remain, but all changes I made in Peppermint are lost. Tried making some more changes, saved again: same result.

**Comment by osxpeppermint** [comment]
OK, bad news. But: given that there were changes from another editor, this basically proves my suspicions were right. Please, give me some time and I'll see what went wrong with change-tracking.

**Comment by rcrooks** [comment]
I may not have been clear — I created the original file in another editor,
but the changes I made that disappeared were all in Peppermint

On Tuesday, January 6, 2015, Peppermint - Code Editor for Mac <
notifications@github.com> wrote:
> OK, bad news. But: given that there were changes from another editor,
this basically proves my suspicions were right. Please, give me some time
and I'll see what went wrong with change-tracking.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/xW8CIkvYZDNbfQEob0bOesYJgs88ziF6rEhqReeLymFuSA5AT8oN7EHrrKla-OWz4ARN7fWoiwWsmCJsEgHn6cKdO8H6Yh-jissB4985tIyBjuKe1FUxhnF2a-yxwU2yeu8BgVB9bsMJB4_4pquiR_ZTGwF5Kg=s0-d-e1-ft#https://github.com/notifications/beacon/AAl0YQroELLubGoIHsbuwQ6UnYTB29S_ks5ne-EEgaJpZM4DOBD-.gif
>

-- 
Robert Crooks
Director of Learning Services | P: 617 245 5090 | M: 617-584 6128
Brightcove Inc <http://www.brightcove.com/>

**Comment by osxpeppermint** [comment]
Hmm.. So we're actually talking about editing a file, in Peppermint, without any external changes whatsoever (while it was opened in Peppermint)?

**Comment by rcrooks** [comment]
That’s correct :(

On Tuesday, January 6, 2015, Peppermint - Code Editor for Mac <
notifications@github.com> wrote:
> Hmm.. So we're actually talking about editing a file, in Peppermint,
without any external changes whatsoever (while it was opened in Peppermint)?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/SIEdIC28aCUuykEdnGwi0scE8CE3yuxknquxJP-0WemecjHjQTfv7-ZNgYr89rQ-sfQDaSJ-yIRewS1vAnOTEA-mfr1DVvmgjBQCyHcCQS-mCUGZWgLm7euolKUS9ru2kGkPEHT-S-U-QMVzbcg8uKKC4vynYQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAl0YeZNdlfwh_ZSksdTH1EP_kStsn-iks5ne_0fgaJpZM4DOBD-.gif
>

-- 
Robert Crooks
Director of Learning Services | P: 617 245 5090 | M: 617-584 6128
Brightcove Inc <http://www.brightcove.com/>

**Comment by rcrooks** [comment]
I experimented some more -- it gets worse :( I opened the same file again, added a line, saved via CMD-s. Same result, and according the tab, the file was not saved. I tried saving via the File menu instead -- my new line reappeared! Still the tab indicates it is not saved. I save again via the File menu - my new line disappears again. So I try saving one more time -- now the entire contents disappear! And worse: I go to finder to look at the file -- the file info indicates that it is brand new, has no history!

I can't figure out what in the world could be going on, and why only I am seeing it. The only thing I can think of: a few days ago, about the first time I saw this happen, I installed Path Finder on this system. Could there be some bad interaction there? But I haven't seen anything similar happen in any other app. This is a mystery....

**Comment by rcrooks** [comment]
Uninstalled Path Finder and restarted, but still seeing the same behavior .... so Path Finder isn't the culprit.

**Comment by rcrooks** [comment]
Just to let you know, this is still happening for me. Tested again today: opened an HTML file, removed a blank line, and saved. That one was fine. Removed another blank line, saved, and it appeared to work, but then nanoseconds later, the contents disappeared.

**Comment by osxpeppermint** [comment]
Robert, I'll have a look - I still feel it has to do with automatic external-change detection.

After my short... relocation break, by next week, you will be seeing updates and betas coming again! :)

Cheers from Barcelona! :)

**Comment by rcrooks** [comment]
cool. Hope the relocation has gone well.


by the way, I didn’t make any external changes to the file in question — it was all in Peppermint.


Cheers!




  

Robert CrooksDirector of Learning Services
Brightcove, Inc

**Comment by SoxIn4** [comment]
I'm seeing similar behavior with bash and python scripts. Whenever I open and edit a file, my edits are lost on save. Sometimes it will keep a letter or two, and sometimes it will let me delete a word, but more often than not, any additions or deletions are reverted when I save.

If I create a new file, I can edit and save as expected, but once I close it and reopen it, I can never save changes with Peppermint again. These files can be opened and edited without issue in other editors.

I'm on version 1.5 build 3632 
Please find a fix! This was quickly becoming my favorite editor before this issue appeared for me in the last week, but I can't use an editor that can't save!

**Comment by SoxIn4** [comment]
I tested editing and saving a file again today after a fresh reboot. It did not go well, but I'm hoping the info can help. I didn't mention in my last comment that I'm on 10.10.2.

* I opened a 120 line markdown file, typed _test_ in the first line after the title and saved.
* _test_ disappeared
* I typed _fffff_ a few lines down and hit save
* _fffff_ disappeared and _test_ reappeared at the top
* I deleted an previously saved word and saved.
* the word reappeared, and so did _fffff_
* I hit undo, and _test_ disappeared
* I hit undo again, and _fffff_ disappeared, and a single _f_ appeared appended to the word I deleted a few steps before
* I hit save, and **all text in my document disappeared**, except for 1 line, "ftest fffff"
* I closed the file (it did **not** prompt me to save) and opened it in another editor.
* It contained a single "f"

I can still open a new file from within Peppermint and edit and save it as much as I please without issues. I enjoy using it enough that I still use it when creating and working on new files, but I have to switch to something else the first time I close the file.

**Comment by osxpeppermint** [comment]
Well, after a lot of time, this bug - as of beta 7 (about to release in some hours) - has been fixed.

So, it is being marked as closed. In any case anything similar happens, I will have that re-opened.

**Comment by rcrooks** [comment]
Fabulous!
