### ISSUE TITLE
Folder Deletions Not Tracked

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#29]
A folder deleted in the Finder is not picked up by the file pane in Peppermint 1.5b4 (build 3608).

**Comment by osxpeppermint** [comment]
Hmm... Let me see if I can reproduce it. I was almost sure folder tracking worked too - at least up to the 3rd beta. I just hope I didn't mess things up with content tracking implementation of the 4th Beta....

**Comment by bobrocke** [comment]
It's working for me in 1.5b5.

**Comment by osxpeppermint** [comment]
Tweaked and revisited as of Beta 6. This should be considered fixed - if there's any issue, just let me know.
