### ISSUE TITLE
Indentation Options Don't Match (Menu vs. Preferences)

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#30]
In Preferences->Editor indentation can be set for 2, 3, 4, 8 or 12 spaces. On the View->Tabs menu it's on 2, 4, 8, 12.

I think I would be better if the option were only on the Preferences pane and that the user could type in however many spaces they wanted. Maybe 1 or 5.

Or the option list were just 1, 2, 3, 4, 5, 6. That should cover everyone.

**Comment by osxpeppermint** [comment]
Hmm. Good catch. Hadn't noticed it.

As for letting the user input whatever you wishes, that's what I'd prefer too. Though this would make the menu (under View) rather... weird - and I was thinking of keeping it... Let's see...

**Comment by bobrocke** [comment]
Or just go with a fixed list in both places: 1, 2, 3, 4, 5, 6

**Comment by osxpeppermint** [comment]
That's exactly what I was thinking right now. :)

**Comment by osxpeppermint** [comment]
Just resolved this by setting Spaces option to [1,2,3,4,5,6,7,8] in both the Preferences window and the menu. (Of course, in the preferences, the user is still able to manually set it to whatever value you wish).

I'm not sure this looks to me as the most elegant solution - but let's see...

**Comment by bobrocke** [comment]
Somewhat more elegant might be fewer choices. For me, it seems unlikely to need indentation larger than 4 spaces. What do you think?

**Comment by osxpeppermint** [comment]
Well, I thought of that too... much less "12" (which was the earlier upper limit). So, I'm with you. But let's see how it goes. Ideas everyone?
