### ISSUE TITLE
The Sass Linter Flags Non-Errors

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#31]
I get this in an .scss file:

![linter](https://cloud.githubusercontent.com/assets/2962426/5606075/307acc92-93ea-11e4-9b2a-7fcb6f98e163.jpeg)

Lot's of non-errors flagged.

**Comment by osxpeppermint** [comment]
Hmm. Basically because the active spec is set to SASS. So, given their subtle differences, that's why brackets and semi-colons appear as error. 

Well, I don't know... perhaps I should create a separate SCSS spec?

**Comment by bobrocke** [comment]
I'd say yes, add a spec for the .scss format.

**Comment by osxpeppermint** [comment]
SCSS Spec added in Beta 5.
