### ISSUE TITLE
Odd console.log output formating

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#32]
Doing  a simple for script produces odd result display:

for (var i = 0; i < 10; i++){ 
console.log(i); 
}

First return:
0
 
1
 
2
 
3
 
4
 
5
 
6
 
7
 
8
9

Second:
1
 
2
 
3
 
4
5
 
6
 
7
8
 
9

Third:
0
 
1
 
2
 
3
 
4
 
5
6
7
8
9

**Comment by osxpeppermint** [comment]
**Questions:**

- Is it 1.4 or 1.5?
- I guess you're talking about JavaScript/Node.js. Have you tried something like that in the terminal (with `$Terminal.echo(i);` instead of `console.log`) and still had issues? (Just tried it and it seems to be working ok).

**Comment by 3l3phant** [comment]
Terminal.echo works perfectly :)
