### ISSUE TITLE
Tab bar closing

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#33]
When closing a tab via the "x" on the tab, the tab disappears but the content in the editor remains. I tried opening multiple tabs to see what happens when closing one but it won't let me. Instead the new tab simply replaces the existing tab (in effect, closing the window but without prompting for a save.)

**Comment by osxpeppermint** [comment]
Well, I guess you're talking about 1.4 (and not the 1.5 beta), right?

If this is the case, this (along with 100 other issues) was one of the... extreme makeover. :)
