### ISSUE TITLE
curl for "https" resource

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#35]
Doing a curl for an https:// resource and receive the following error:

curl: (1) Protoco
l 'https not supported or disabled in lib
curl

(Note - the command responds properly in terminal.app)

**Comment by osxpeppermint** [comment]
Hmm... I'll have a look into - although, to be honest, I haven't tried "curl" so far via the Peppermint's terminal.

**Comment by osxpeppermint** [comment]
As silly as it may seem, would you mind giving a try to the solution suggested here: http://bartwullems.blogspot.com.es/2013/08/curl-1-protocol-not-supported-or.html

It may totally be irrelevant, but the guy there suggests it could even be a quote-related issue. Please,  in case you have some time and try it out, just let me know how it went... :)
