### ISSUE TITLE
Open Documents Not Tracked

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#38]
Quit Peppermint with files open. Relaunch Peppermint. The files that were open on quit are not re-opened on launch.

**Comment by osxpeppermint** [comment]
Hmm... Does this concern single files only? Folders only? Both? (Have you made sure the related property is set in the Prefences window?)

**Comment by bobrocke** [comment]
It is set in preferences.

The file pane opens with the right stuff in it.But any files that were open for editing on quit are not re-opened on launch.

**Comment by osxpeppermint** [comment]
Delayed... clarification needed:

Do you mean the files that are opened as tabs? (a.k.a. opened for editing)

And if so, would that be a desired universal behavior? Or would you prefer if this (opening - not in the file pane, but in the tabs as well - previously-opened document) be set as another Preferences option as well?

**Comment by bobrocke** [comment]
Yes, the files that were open for editing are not on a relaunch.

For me, I'd like it as a default. But others may rather it be a preference. Either way is fine.

**Comment by osxpeppermint** [comment]
Aham. OK. Thanks for clarifying... 

I was bit confused thinking that some of the sidebar items did not reappear on launch. :)

**Comment by osxpeppermint** [comment]
Issue resolved as of the upcoming 1.5 beta 17.
