### ISSUE TITLE
File System Changes Add To The Bottom Of the Files Pane

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#39]
They do. They should be added in the pane where they are to be: folders at the top in alpha order, files under them in alpha order.

**Comment by osxpeppermint** [comment]
That's correct. I know about it and I was going to fix it. Thanks a lot for reminding me! :-)

**Comment by osxpeppermint** [comment]
Fixed as of the upcoming 1.5 - beta 6. :)
