### ISSUE TITLE
Regular expression group replace

### ISSUE THREAD

**Issue by GerTeunis** [osxpeppermint/peppermint#42]
Regular expression replace with group number replace doesn't work.

I.e. the text:
"Hello world how are you"

Match using regex:
.*(world).*

replace with
Poop \1 stinky

Does replace the text to
Poop \1 stinky

and not
Poop world stinky

**Comment by osxpeppermint** [comment]
Well, this is a hard one. I know exactly what you mean, but right now it's most definitely not supported -- regex replace sure, but not taking into account the groups.

I'll see what can be done...

**Comment by osxpeppermint** [comment]
Implemented as of the upcoming 1.5 beta 21. :)
