### ISSUE TITLE
Drag-and-drop

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#46]
Would love to be able to drag-and-drop files from the finder into the workspace.

**Comment by osxpeppermint** [comment]
This is currently in my to-do list.

Once I sort out a few - more important - issues, drag'n'drop will sure find its way into the workspace sidebar. :)

**Comment by osxpeppermint** [comment]
Feature implemented as of the upcoming 1.5 Beta 15.

----

P.S. Drag'n'drop from Finder to Workspace subfolders (a.k.a. copy-pasting as well) + drag'n'drop from Workspace to Workspace is to be considered as a future addition.
