### ISSUE TITLE
Automated undo?

### ISSUE THREAD

**Issue by 3l3phant** [osxpeppermint/peppermint#47]
For some reason after changing a line in my code and then saving it modifies the line. This one is taught explain, so see attached. The first image has top and left set to 10%. When I try and change it from (I think) 20px (the second image) autosuggest pops up. I hit <esc>, keep it at 10% and then hit save. The number switches to 1% (third image). I'm not sure if that makes sense but it's annoying. It won't let me save the file with the variable set the way I need it to be.
![pre-save](https://cloud.githubusercontent.com/assets/10382240/6203907/ee07864c-b505-11e4-9bbf-0feb6e8fc128.png)
![during_edit](https://cloud.githubusercontent.com/assets/10382240/6203918/33432036-b506-11e4-8327-f4d82c37aa08.png)

![post_save](https://cloud.githubusercontent.com/assets/10382240/6203906/ee0436b8-b505-11e4-87fe-d1de90d6610d.png)

**Comment by osxpeppermint** [comment]
It still looks impossible to reproduce this one. I really have no idea what might be going on...

**Comment by 3l3phant** [comment]
I'll try and reproduce on a newer version (to be honest I haven't really used the application in a while. Haven't had any coding projects lately :))

**Comment by osxpeppermint** [comment]
Issue closely related with https://github.com/osxpeppermint/peppermint/issues/27 - which has (seemingly) already been resolved.
