### ISSUE TITLE
Find dialog

### ISSUE THREAD

**Issue by corelon** [osxpeppermint/peppermint#48]
Hello,

I am trying to Command-F (or even from the menu) and I would expect to see a find dialog. Instead it seems to be behaving like Command-E (find from selection). 
Also replace does not show anything. Is this the intended behaviour? Am I missing something?

I am using 1.5 (Build 3632) on Yosemite (10.10.3) on a Macbook Pro.

**Comment by corelon** [comment]
Just realised that I need to explicitly open the search panel. I think the search panel should come up with Command-F. It can be a bit misleading.

My two cents.

**Comment by corelon** [comment]
Sorry for the continuous update of this ticket.
Just checked that Command-F will not get me to the search panel (or Commmand-Option-F) even if the search panel is open. I think this can be classified as a bug.

**Comment by osxpeppermint** [comment]
Apologies for the extreme delay but the last days-weeks-months have been crazy (moving to Spain), but I'm back.

As for the issue, you were 100% right. Right now, (coming as part of the next 1.5 beta 6) when the user tries to search (e.g. pressing <kbd>⌘F</kbd>), we always make sure the search panel is open - and if not, it's being opened automatically.
