### ISSUE TITLE
Peppermint should not quit when the last window is closed

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#50]
At least that's my opinion.

**Comment by osxpeppermint** [comment]
Hmm... I understand what you mean.

So, instead of closing, you suggest the app being minimized to the Dock?

**Comment by bobrocke** [comment]
It could minimize, or just display nothing. Most Mac apps work like that.

**Comment by osxpeppermint** [comment]
> Most Mac apps work like that.

Well, I guess here is where my Windows/Linux past is more than... evident: I never got used to clicking "x" and having the app minimized. lol

But, on a serious note, I know what you mean - and I'll see how I can do. It does make sense.

**Comment by osxpeppermint** [comment]
Implemented as of the upcoming 1.5 Beta 15.
