### ISSUE TITLE
Workspace Excluded Files

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#51]
I would like the excluded files pane to scroll as the length of the list grows.

I would also like it to be read when the Reload Extensions command runs.

**Comment by bobrocke** [comment]
Are excluded files on a global or project basis? I'd like them to apply at the project level.

It would be even better if there were global AND project level excludes.

**Comment by osxpeppermint** [comment]
Hmm... I'm not sure what you mean...

This is what you're referring to, right?
![screen shot 2015-05-16 at 3 08 12 pm](https://cloud.githubusercontent.com/assets/9476915/7666235/59f7b32c-fbdd-11e4-9ee1-e6281a73676d.png)

**Comment by bobrocke** [comment]
Yes.

I'd like the pane to have a scroll so long exclude lists are easier to deal with.

And, it would be extra cool if there were two: one for all projects (global preference) and one for the current project (local preference).

**Comment by osxpeppermint** [comment]
Part 1 (scrolling) of the suggestion has just been implemented. So it'll be included in the very next beta (10).

As for local/project-specific filtering, I find that a little bit confusing... How could it work project-wise while being set globally? Could you elaborate a bit on how you would expect this to be working?

**Comment by bobrocke** [comment]
As I see it, there would be two sets of preferences. The global set would apply to any folder or file.

The project preferences could override, or add to, the global preference and would apply to the active project only.

By project, I'm thinking of the current "folder," like this:

![peppermint](https://cloud.githubusercontent.com/assets/2962426/7666281/2748df16-fbae-11e4-9874-bbdb68cc6fa8.jpg)

**Comment by osxpeppermint** [comment]
Hmm... I see what you mean...

How I see it, applying an (additional) specified filter to the active (how is this to be determined?) project would complicate things.

What I could think though is to have an additional set of filters for the active project being *selected*, meaning:

![screen shot 2015-05-16 at 3 36 17 pm](https://cloud.githubusercontent.com/assets/9476915/7666315/8f6d0486-fbe1-11e4-99ff-b0472b8d39bb.png)

![screen shot 2015-05-16 at 3 37 40 pm](https://cloud.githubusercontent.com/assets/9476915/7666317/92c2f99c-fbe1-11e4-9e86-2259073305ab.png)

Does that make any sense?

**Comment by bobrocke** [comment]
That could work, but might be weird if certain folders were excluded in the Workspace view, but not in individual project views.

Maybe in Workspace view only global excludes are available in preferences and in project views, both are available and labeled as such?

**Comment by osxpeppermint** [comment]
Hmm... Yep, that's what I meant (I believe we're on the same page):

- Global filters -> Workspace
- Global+Project filters -> Projects

**Comment by osxpeppermint** [comment]
Feature implemented as of the upcoming 1.5 beta 19 (as part of the EditorConfig integration).

The same way .editorconfig files are used, Peppermint will be allowing to "filter" specific files, like:

    [*.js]
    pp_filter_file = true

And that's it. So, it'll be both easy-to-edit and project-specific (adding to the already existing Workspace filter settings).

**Comment by bobrocke** [comment]
This looks like it should work well.

Where does one put the configuration? In a project settings file or some sort? In the little text field of the Preferences > Files pane?

**Comment by osxpeppermint** [comment]
Well... here's what:

- In the Preferences > Files pane, you can set the filters as you used to. But those are the global ones
- Your project-(or even folder-)specific filters can be set in your .editorconfig file. So, the same way you have e.g.:

    [*.js]
    indent_style = space
    indent_size = 4

And the settings being applied to every sub-file, you can also set (yep, inside the .editorconfig file) which files you want to filter (as I showed in the message above). ;-)

**Comment by bobrocke** [comment]
OK, I get it! Nice.

Is the plan to put other (perhaps future) project related Peppermint configuration in the .editorconfig file?

**Comment by osxpeppermint** [comment]
> Is the plan to put other (perhaps future) project related Peppermint configuration in the .editorconfig file?

Of course! And I'm open to suggestions... :)
