### ISSUE TITLE
Display Image Size

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#53]
When an image file is selected and previewed, display the pixel dimensions, too.

**Comment by osxpeppermint** [comment]
Yep, that's a great point.

P.S. I know it's missing, but given that image-preview is a relative fresh feature, the truth is there are TONS of things I still want to add/tweak/etc... :-)

**Comment by osxpeppermint** [comment]
Initial implementation as of 1.5 Beta 10.
