### ISSUE TITLE
Inspect Element doesn't select the element in Dev Tools

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#58]
If you right-click over part of the editor and select Inspect Element, the Dev Tools pane opens but the item under the cursor is not selected in the source view. Instead, the overall `<textarea>` is selected. I would haver expected/wanted the item under the cursor, deeper in the view hierarchy, was selected.

**Comment by osxpeppermint** [comment]
Well, to be honest, the "Inspect Element" part has been left there for (my) debugging needs - I'm not even sure it's gonna be in the final release or if it should be available to end users. It seems rather confusing (given that the "Terminal" part - which for me is the most useful - is already handled by the Peppermint Console itself).

I don't know...

Any ideas are welcome! :)

**Comment by bobrocke** [comment]
I would like to see it in the final release; I use the equivalent in Brackets and Atom all the time.

I would like to right-click and Inspect Element and see the exact line in the Dev Tools view. I want to see what styles have been applied that I might want to target with my theme.

**Comment by osxpeppermint** [comment]
Hmm... I know what you mean and it can definitely be done.

The thing is that, given that the Peppermint core is based on Ace, Inspecting the editor itself means you have to drill down the whole Ace structure (and this might not be that obvious at first sight): editor -> ace_scroller -> ace_text-layer

However, it's still possible to see every single like, with all the tokens, and the styles being applied.

Have a look:

![screen shot 2015-06-20 at 11 33 30 am](https://cloud.githubusercontent.com/assets/9476915/8266752/03791ed6-1740-11e5-87f1-07cbd7a08e5e.png)

**Comment by osxpeppermint** [comment]
I marking this as closed.

Regarding future integration, what I'm thinking of is removing it from the Right-Click menu (it doesn't look good to me), and adding it - perhaps - as a Developer Mode option. Don't know. But as you said, it 's not such a bad idea if remains available. :)

**Comment by osxpeppermint** [comment]
Btw... for getting what type of CSS style goes to what keyword (it's not in the API - yet - but you can still use it), you can use: `pp.editor.tokenize()`

Or, as a more complete example, just copy-paste into the (Coffee) Console:

    $Terminal.echo("#{ token.v } = #{ token.t }") for token in pp.editor.tokenize();

And here it is in action:

![screen shot 2015-06-20 at 1 17 41 pm](https://cloud.githubusercontent.com/assets/9476915/8267020/e28c1c96-174e-11e5-9f03-ce145e0cd029.png)

**Comment by bobrocke** [comment]
Brackets uses CodeMirror as its editor and has the same problem drilling down into CodeMirror's DOM. There is an extension for Brackets (Brackets-InspectEditor at https://github.com/MiguelCastillo/Brackets-InspectEditor) that enables the ability for Brackets. Could it be modified for Peppermint?

**Comment by osxpeppermint** [comment]
Hm, Hm, Hm... Believe it or not I had no idea CM was behind Brackets. I guess I have to have another look into it. Let me see...
