### ISSUE TITLE
Open dialog should show hidden files?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#60]
I think a programmers' editor's Open dialog should default to show hidden files and allow packages to be navigated into.

**Comment by osxpeppermint** [comment]
Well... I get your point, but I believe Peppermint already does that:

- Hidden files are shown
- Package (most of them I believe) can ben navigated to

![screen shot 2015-06-19 at 1 12 17 pm](https://cloud.githubusercontent.com/assets/9476915/8252249/960871fa-1684-11e5-8ef4-37ed481ba0cc.png)

Can you give me an example where it didn't work?

**Comment by bobrocke** [comment]
I can't drill down into the Peppermint app package:

![monosnap](https://cloud.githubusercontent.com/assets/2962426/8262629/a6d3a5a0-16a1-11e5-86ef-5196d8ea3ef4.jpg)

**Comment by osxpeppermint** [comment]
Hmm... Didn't try it with App packages, to be honest.

I'll have a look into it.

**Comment by osxpeppermint** [comment]
OK, done and implemented as of the upcoming 1.5 Beta 17. :)

![screen shot 2015-06-20 at 1 07 42 pm](https://cloud.githubusercontent.com/assets/9476915/8267001/3732deb2-174d-11e5-967f-1d54697016a8.png)

**Comment by bobrocke** [comment]
Fast!

When do you expect to release beta 17?

**Comment by osxpeppermint** [comment]
Well,... today. (3-4 more hours, max.) :)

P.S. That's the goal of the betas anyway, isn't it? Write->Deliver->Test->Debug (and Repeat - as fast as possible)
