### ISSUE TITLE
Custom file tree pane icons for Twig files?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#61]
Now `.html.twig` files get a generic icon. Can we have a custom icon for those files?

**Comment by osxpeppermint** [comment]
Well... no matter what the file type, OSX files get their icon once an application (that has the role of opening/editing them) "assigns" them that icon.

Right now, Peppermint assigns no icon to any filetype whatsoever. It just picks the default ones already existing. However, I *have* been designing filetype icons and I'm soon thinking of integrating them too. So... I will add a "twig" one as well. ;-)

**Comment by bobrocke** [comment]
Oh, OK. I'm alright with using the Finder's icon. That may be best, after all.
