### ISSUE TITLE
Create new window

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#63]
I'd like to be able to open multiple windows.

**Comment by osxpeppermint** [comment]
Well, this is an interesting suggestion - and I know it's missing.

However, since it'll require some more... core tweaks, I'm leaving it in the to-do queue until more critical things are resolved. :)

**Comment by bobrocke** [comment]
OK. But a Mac app that can't do multiple windows is an odd Mac app.

**Comment by osxpeppermint** [comment]
You do have a point...

**Comment by osxpeppermint** [comment]
Closed as a duplicate of https://github.com/osxpeppermint/peppermint/issues/85
