### ISSUE TITLE
API for the system clipboard

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#66]
I'd like to be able to read the system clipboard from within a Peppermint plugin. Possible?

**Comment by osxpeppermint** [comment]
Well, this is an awesome idea and it should be very easy to implement. Let me see what I can do...

**Comment by osxpeppermint** [comment]
Implemented, as of the upcoming 1.5 Beta 17, within the `$Editor` class, so that you can:

- get the clipboard contents via `$Editor.clipboard()`
- set the clipboard contents via `$Editor.clipboard("new clipboard contents")`

**Comment by bobrocke** [comment]
Fast work! Thanks!
