### ISSUE TITLE
Linters?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#67]
The official Peppermint web pages doesn't show any linters available. But several languages do appear to have live linting. What linters are available? Can additional linters be added by the user?

**Comment by bobrocke** [comment]
Found what I needed.

**Comment by osxpeppermint** [comment]
Well, the truth is I have missed updating the official page (basically, until I add more).

As for "Linters", they are developed as Builtins (basically a Plugin, same thing/structure/everything, with the only difference being that it is not triggered by the user, but is instead "attached" to a specific Spec).

If you have a look into Data/Builtins/Haxe, you'll see a good example of a Parser (what is used for the syntax tree) and a Linter. For adding a custom user-builtin (that will not get deleted on a future Peppermint update), you just have to put it under `User/Builtins/SPEC-NAME`.

P.S. Very soon, I'll make Builtins installable via the UI (basically via the Extension Manager), pretty much as it happens with Plugins.
