### ISSUE TITLE
How quickly are ACE releases integrated with Peppermint?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#68]
Or can a new release of ACE be simply inserted into Peppermint by the user.

**Comment by osxpeppermint** [comment]
Well, having the Ace releases going directly into Peppermint (e.g. by the user - as you say) would be close to impossible. Given that every time a new release comes out, there are things that *have* to be tweaked (it most definitely requires a number of modifications and it does not work 100% out-of-the-box).

However, given some recent changes in the Peppermint core, new Ace releases are easier than ever to integrate -- so whenever there is a new Ace release, it'll most likely be integrated in the very next Peppermint release too (be it a beta or not).

**Comment by bobrocke** [comment]
I figured. Brackets has its own interface to CodeMirror - you can't just plug in CodeMirror updated there either. But you can sneak in CodeMirror mode updates. ;)

**Comment by osxpeppermint** [comment]
CodeMirror is an interesting Ace branch, indeed. And there is some interchange-ability. However, not at a 100%. I made the decision to use Ace (instead of CM) a long time ago, and this cannot change that easily anymore. Not that I regret it by any means... :)

**Comment by bobrocke** [comment]
No, as far as I can tell ACE is just fine. I'm not suggesting a change.
