### ISSUE TITLE
cursor jumps to top of file

### ISSUE THREAD

**Issue by rcrooks** [osxpeppermint/peppermint#71]
First wanted to say that the latest betas show great progress - Peppermint is growing up fast!

I am having an odd issue: I open a file (in this case it's HTML), go to point where I want to start editing, and start typing. The first character is entered where I want it, then the cursor jump to the top of the file and starts inserting additional characters there. I don't know yet if this is consistent behavior, but it's happened to me twice in the past day.

**Comment by rcrooks** [comment]
ps. also seeing cursor jump to the top of the file when I save -- maybe related?

**Comment by osxpeppermint** [comment]
Well, Robert... First of all, thanks a lot for your kind words. Yep, after my "break", I'm 100% back and working really hard to bring it to the next level. So, here we are.

Unfortunately, what you mention is a (recent) known bug and at the very top of my list. I have spotted that too and it might be a bit more challenging than it initially sounds - but I'll make it. I'm making an "intermediate" release today, but the next one will most likely have that fixed.

P.S. And yes, the think with the "Save" is related. (Along with a weird issue with Undo: You can undo *everything* but the very first change. So, all three of them stem from the very same bug.)

**Comment by osxpeppermint** [comment]
Hopefully, resolved as of the upcoming 1.5 beta 18.

P.S. If there's still any issue (once I upload the next release), just let me know and I'll re-open the issue.
