### ISSUE TITLE
Bracket matching?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#73]
Peppermint doesn't seem to have bracket matching - highlighting the matching bracket when to cursor is near a bracket (or parenthesis). Am I missing a setting?

**Comment by osxpeppermint** [comment]
Well, bracket matching is enabled. It all depends on the theme (if the theme doesn't style the appropriate part `.marker-layer .bracket`, then bracket matching cannot be seen). The default Peppermint theme most definitely supports it (though it might seem a bit... subtle).

Here's bracket matching and the relevant part of the `style.less` of the Peppermint theme:

![bracket-matching](https://cloud.githubusercontent.com/assets/9476915/8271048/a75d2ea8-1802-11e5-9142-6c38ea8cb385.png)
