### ISSUE TITLE
Xdebug plugin

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#75]
Peppermint could really use an Xdebug plugin to make PHP development easier. here's an example:

https://github.com/spocke/php-debugger

**Comment by osxpeppermint** [comment]
Yep, I know about Xdebug and comes really handy when talking about PHP development - so it already is in my to-do list... ;)

**Comment by osxpeppermint** [comment]
Closed as a duplicate of https://github.com/osxpeppermint/peppermint/issues/83
