### ISSUE TITLE
Warn on quitting Peppermint without saving changes to new file

### ISSUE THREAD

**Issue by rcrooks** [osxpeppermint/peppermint#76]
It's not that hard to absent-mindedly press CMD-Q when you meant to press CMD-S :)

**Comment by osxpeppermint** [comment]
Well, I'm 100% sure I had fixed this one at some point, but then change something else and there we go again... What can I say... 

Thanks for letting me know! :)

**Comment by osxpeppermint** [comment]
Fixed as of the upcoming 1.5 beta 18.

P.S. The idea so far is to checked for unsaved changes and throw a warning (whether the user wants to proceed or cancel the process). However, it *is* going to be revisited (e.g. by showing a list of modified files and letting the user decide which ones to save? by going through the unsaved files with a "Save: Yes/No" dialog?)
