### ISSUE TITLE
Key feature comparison

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#77]
Here's how several current editors stack up for key features (from my point of view). Many important features that are implemented by all are not shown.

For me, there's not a clear "winner." Where do these, and other, features rank on other users' priorities?

![editor table](https://cloud.githubusercontent.com/assets/2962426/8271944/1f10c0c6-17ff-11e5-906b-07b3e2ce6978.jpg)

**Comment by osxpeppermint** [comment]
Well, even if I can see the "subjective" part of it (everyone has a few things he needs more than others - me included),... amazing work. :)

I've been thinking of doing something along these lines - just including every possible "feature" I can think of. Your list however could definitely stand as a WebDeveloper-oriented list. I can see your point and I'll see which of those... red boxes I can eliminate... ;-)

**Comment by bobrocke** [comment]
Yes, **very** subjective. Every user will have their own, very possibly different, priorities. And a red box for someone, might be a yellow box for someone else.

I wanted to start a conversation, not be critical. And that's how you took it. :)

**Comment by osxpeppermint** [comment]
(Well, if there's any misunderstanding here... I just hope everyone was as... critical as you are. This is my "fuel" - and the only way to make it better. So, keep it coming - it's more than welcome! :) )

**Comment by bobrocke** [comment]
I've updated the grid adding TextMate and Sublime Text 3.

**Comment by osxpeppermint** [comment]
Gets even more interesting.

I might upload an excel at google docs too, at some point - very good for tracking our progress and where Peppermint stands. :)

**Comment by osxpeppermint** [comment]
* LESS Linter (Live syntax checking) added as of the upcoming 1.5 beta 18.

**Comment by osxpeppermint** [comment]
Question: Can you please elaborate on what you mean by "Show scope command"?

**Comment by osxpeppermint** [comment]
* YAML Linter (Live syntax checking) added as of the upcoming 1.5 beta 18.

Also, regarding YAML:

- Added Code/Symbol Navigation
- Added "Preview" plugin
- Added "Convert to JSON" plugin

**Comment by bobrocke** [comment]
The "Show Scope Command" allows you to see the scope cascade for a selected item in the editor. It's a streamlined way to get the CSS classes assigned and it's very handy.

And nice progress on live linters in a short time!

**Comment by osxpeppermint** [comment]
Thanks a lot! I'm doing my best! :)

Re: "Show scope", I'll have to have a look into it. I *think* I know what you mean, but I'll have to see it in action.

------

P.S. Re: EditorConfig, it's finally here. :) See: https://github.com/osxpeppermint/peppermint/issues/15

**Comment by bobrocke** [comment]
Good news on EditorConfig!

To see Show Scope, try out Scope Hunter in Sublime Text 3.

**Comment by osxpeppermint** [comment]
Hmm... I just did try it.

The question is: why is this needed?

------

P.S. If it is for theming purposes, well... This is one of the next things I'm thinking of including in the Theme Creator plugin (= the option to be able to hover over an element and see what class goes to it). Why implement it as a separate functionality?

**Comment by osxpeppermint** [comment]
- SCSS Linter (Live syntax checking) added as of the upcoming 1.5 beta 19.

Also, regarding SCSS:

- Added "Preview" plugin
- Added "Compile" plugin

**Comment by bobrocke** [comment]
The "Show Scope" utility is for grammar(syntax) and theme development. You can see what CSS to target in your theme and/or you can see what CSS is being applied by the grammar.

If you could easily select an element the DOM created by Ace, you could so the same thing.

**Comment by osxpeppermint** [comment]
"Show scope" incorporated in Theme Creator as of the upcoming 1.5 beta 19.

And here's an overview of how it works... 

![tokentooltips](https://cloud.githubusercontent.com/assets/9476915/8334548/d5b3c0a8-1a98-11e5-87e7-25d593699bec.png)


P.S. Once I figure out how to make Grammar editing easy for anyone, I might incorporate into that plugin too. ;-)

**Comment by bobrocke** [comment]
More progress! I hope beta 19 is out soon - I'll have to update my matrix and repost! :)

**Comment by bobrocke** [comment]
Looking good. My personal matrix looks like this now:

![editor table](https://cloud.githubusercontent.com/assets/2962426/8382545/4f954252-1c01-11e5-9506-6bc3fe5acb6e.jpg)

The Show Token Tooltips option will go well with the planned ability for the Theme Creator to also be a Theme Editor.

With so much done, should I close this issue and open new, specific, issues for new feature suggestions from the matrix?

**Comment by osxpeppermint** [comment]
Well, to be honest, the way I work (and trust me I have loads of plain-old-paper to-do lists sitting on my desk) one issue per... specific issue is prefered. It helps me manage them better than having to dig into a specific issue and see what's left to be done. 

P.S. Thanks for all the help! :)
