### ISSUE TITLE
Slack or Gitter?

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#81]
Do you think the community around Peppermint has grown to the point that a chat service such as Gitter or Slack would be beneficial?

**Comment by osxpeppermint** [comment]
Well, this is an interesting question. I really don't know: Peppermint is already [on Gitter](https://gitter.im/osxpeppermint/peppermint?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and obviously here in GitHub issues. The weird thing is that most... discussion still goes on through my mails (not really practical, but I'm still grateful... :-) )
