### ISSUE TITLE
Editing themes

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#88]
I created a new theme (Bob's Colors) with the Theme Creator and saved it. That produced `~/Library/Application Support/Peppermint/User/Themes/Bob’s Colors.ppTheme/style.less`

But when I open and edit the `style.less` files, save and restart Peppermint, the changes are not taking effect.

Where am I going wrong?

**Comment by osxpeppermint** [comment]
Well, my very first guess (and I'm pretty sure I'm right), you're doing nothing wrong. It's just that I haven't predicted spaces or weird characters (`'`) within the Theme Name. 

I'll have a look into it and fix it.

**Comment by osxpeppermint** [comment]
Issue fixed as of the upcoming 1.5 beta 20.
