### ISSUE TITLE
Workspace files don't behave on launch

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#91]
1) Add a file to the workspace that is outside the project folder
2) Open it
3) Close it but keep it as part of the workspace
4) Quit
5) Relaunch Peppermint

The file in the workspace is opened, it shouldn't be, and the contents are empty.

**Comment by osxpeppermint** [comment]
Well, this sounds a bit weird...

Right now, the way Peppermint works (if the appropriate Preferences setting is on) is to:

- "Remember" the files in Workspace (so, it reloads them)
- "Remember" the opened files (so, it re-opens them).

If the file was in the workspace, then it was logically re-loaded. As for the contents, I'm a bit confused: you mean you tried to view its contents and nothing was there the next time?

**Comment by bobrocke** [comment]
I think that only open files on quit should be re-opened on re-launch.

It looks like this:

![open-a-terminal js peppermint](https://cloud.githubusercontent.com/assets/2962426/8411359/9dcd0336-1e51-11e5-868f-a9b906e3dca6.jpg)

If I close it, remove it from the workspace, and then re-open it, its contents are there.

**Comment by osxpeppermint** [comment]
Aham... So you mean it was re-loaded (in the Workspace) and re-opened (as a tab) even if you had closed the tab?

That's even more weird. Did you close the application normally or did you force-quit it before all of this happened?

**Comment by bobrocke** [comment]
I expected that the file would stay in the workspace, and it did. But I had closed its tab and on re-launch the tab was re-opened.

It was a normal command-q quit.

**Comment by osxpeppermint** [comment]
Hmm Hmm Hmm. That's not normal. I'll have to look into it...

**Comment by osxpeppermint** [comment]
Issue fixed as of 1.5 beta 21.
