### ISSUE TITLE
Custom themes not applied

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#93]
I've started a custom theme and have selected it. But the previous theme is still the one applied:

![stuck](https://cloud.githubusercontent.com/assets/2962426/8482045/f62b357e-20b4-11e5-991e-1d95025a30b3.jpeg)

**Comment by osxpeppermint** [comment]
Can you send me the a zip with the .ppTheme?

**Comment by osxpeppermint** [comment]
Resolved as of the upcoming 1.5 beta 22.
