### ISSUE TITLE
Selecting Preferences from the Peppermint Menu Does Nothing

### ISSUE THREAD

**Issue by paul-sneddon** [osxpeppermint/peppermint#94]
In the Mac App Store, under Mac OS 10.10.4.  Selecting the Preferences menu item under the main Peppermint menu does not open preferences, it does nothing at all.  I tried the non-app store trial version and this functions correctly.

**Comment by drkameleon** [comment]
Paul, Hi!

This is an <del>un</del>known issue with the currently released App Store version - which has long been resolved in the 1.4 (and the 1.5 beta) versions outside MAS.

If you just send me an e-mail (at drkameleon(at)gmail), I can send you your full License credentials.

Just let me know! ;-)
